#!/bin/bash
##Assigns the first positional argument passed to the script to the variable NAME
NAME="${1}" 
#Assigns the second positional argument passed to the script to the variable DOMAIN
DOMAIN="${2}" 
#Defines a variable named OUTPUT_FILE with the name of the CSV file where results will be stored
OUTPUT_FILE="results.csv"
#Checks if either the NAME variable or the DOMAIN variable is empty (-z). If true, it starts the conditional block
if [[ -z "${NAME}" ]] || [[ -z "${DOMAIN}" ]]; then
#Prints an error message explaining that two arguments are required to run the script
  echo "You must provide two arguments to this script."
  #Prints a usage example on how to run the script, where ${0} represents the script's own filename
  echo "Example: ${0} mysite nostarch.com"
  #Terminates the script execution immediately with an error exit code of 1
  exit 1
fi #Closes the initial if statement block that validated the arguments

#Writes the column headers into the CSV file. The single > redirection operator overwrites the file if it already exists.
echo "status,name,domain,timestamp" > ${OUTPUT_FILE}

#Sends a single ping request (-c 1) to the specified domain. It redirects both standard output and error (&>) to /dev/null to keep it silent. If the ping succeeds, it executes the then block
if ping -c 1 "${DOMAIN}" &> /dev/null; then
#Appends (>>) a comma-separated row to the output file indicating a successful connection, including the current timestamp generated by $(date)
  echo "success,${NAME},${DOMAIN},$(date)" >> "${OUTPUT_FILE}"
else #Defines the alternative block of code to execute if the ping command fails
#Appends (>>) a comma-separated row to the output file indicating a failed connection attempt along with the current timestamp
  echo "failure,${NAME},${DOMAIN},$(date)" >> "${OUTPUT_FILE}"
fi #Closes the if/else statement block used for the network connectivity check.
